# Generated by Django 4.0.6 on 2022-07-27 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_course_options_admin_adcode_admin_mobile_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'ordering': ['Adcode']},
        ),
        migrations.AlterModelOptions(
            name='instructor',
            options={'ordering': ['Icode']},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['entrynumber']},
        ),
    ]
